name: Day
main: com.webkonsept.bukkit.day.Day
version: 0.3
website: http://minecraft.webkonsept.com/plugins/details/Day.jar
location: http://minecraft.webkonsept.com/plugins/download/Day.jar
author: DemmyDemon
database: false
description: Manipulates the rotation of the planet, turning night into day!
commands:
    day:
        aliases: 
        description: Summons the daystar
        usage: /<command> (takes no arguments)
    night:
        aliases:
        description: Plunges the world into darkness
        usage: /<command> (takes no arguments)
bukget: true
build:
    min: 953
    max: 953
categories:
    - MECH