name: Day
main: com.webkonsept.bukkit.day.Day
version: 0.3
branch: stable
thread: http://forums.bukkit.org/threads/Day.24011/
website: http://minecraft.webkonsept.com/plugins/details/Day.html
location: http://minecraft.webkonsept.com/plugins/download/Day.jar
database: false
commands:
    day:
        aliases: 
        description: Summons the daystar
        usage: /<command> (takes no arguments)
    night:
        aliases:
        description: Plunges the world into darkness
        usage: /<command> (takes no arguments)
generators: [bukget]
categories: [MECH]
description: Manipulates the rotation of the planet, turning night into day!
maintainer: DemmyDemon
authors: [DemmyDemon]
conflicts: []
required: []
optional: [Permissions]
engines:
    craftbukkit:
        min: 935
        max: 953
